### ISSUE TITLE
[FEATURE] Consider to use NIP-32

### ISSUE THREAD

**Issue by atrifat** [atrifat/nostr-monitoring-tool#1]
# Issue
Consider to use [NIP-32](https://github.com/nostr-protocol/nips/blob/master/32.md) instead of current implementation using kind 9978. We need to transform data format properly and learn how to apply it based on NIP-32.

# Solution
Implementation Status:
- [x] NIP-32 support for NSFW Classification (Content-safety). Closed with #35 
- [x] NIP-32 support for Language Classification. Closed with #36  
- [x] NIP-32 support for Hate speech Classification (Toxicity). Closed with #37 
- [x] NIP-32 support for Sentiment Classification. Closed with #38 
- [x] NIP-32 support for Topic Classification. Closed with #39

**Comment by atrifat** [comment]
Implementation related to atrifat/nostr-filter-relay#18 .
